version: '3.4'
services:
  conductor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /srv
    volumes:
      - vendor:/srv/vendor
      - ./composer.json:/srv/composer.json
      - ./composer.lock:/srv/composer.lock
      - .:/srv
    command: composer validate-code
volumes:
  vendor:
